version: '3'
services:
  open_fire_sync:
    image: openfire_sync_image
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    command: python -u openfire_sync.py auto
